application: push-demo
version: 1
runtime: php55
api_version: 1
instance_class: f1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  
handlers:
- url: /$
  static_files: index.html
  upload: index.html

- url: /(.*\.(?:png|js|css|html))$
  static_files: \1
  upload: .*
  
skip_files:
- ^(.*/)?\.md$
- ^app.yaml$
- ^.git
